### PR TITLE
Autodesk: Update Text proposal according to comments

### PR DESCRIPTION
**Pull request by erikaharrison-adsk**
### Description of Proposal

Update the proposal according to the comments.

We will focus on the schema in the proposal, not the implementation. So I removed the part about the Rprims, and also the plugins.

Add more detail about the SimpleText and MarkupText schemas. Add how the extents should be implemented.

Add the language tag for the textData in SimpleText and markup in MarkupText, and refer to the language proposal.

Add the "plain" tag for markup which is an alternate string when the markup can not be identified.

Remove the renderer property in SimpleText and MarkupText.

Change the name of the properties in TextStyle. Add altTypeface property which is used when the main typeface can not support some characters.
Add details about the font weight.

The TextLayout and TextLayoutAPI are merged into one schema. The new TextLayoutAPI not only contains the character directions, but also contains the direction how the lines are stacked.

Modify the name of the properties in ColumnStyle. Remove the direction and linesFlowDirection property in ColumnStyle. Instead, you can apply a TextLayoutAPI to a ColumnStyle to specify the directions.

In the part of "Some implementation details", discuss the extrusion, the missing characters, the layout for complex script and the billboard.

Finally there is a big part of four examples.

[Link to Rendered Proposal](https://github.com/autodesk-forks/USD-proposals/blob/adsk/feature/text/proposals/text/README.md)

### Supporting Materials

Previous PRs:

* https://github.com/PixarAnimationStudios/OpenUSD-proposals/pull/48
* https://github.com/PixarAnimationStudios/OpenUSD-proposals/pull/38
* https://github.com/PixarAnimationStudios/OpenUSD-proposals/pull/24

### Contributing

- [X] I agree to and accept the [Supplemental Terms](https://graphics.pixar.com/usd/release/contributing_supplemental.html).

### CODE REVIEW

**Comment by PierreWang** [comment]
@meshula @dgovil @tcauchois @spiffmon
This is the updated text proposal. I hope that all your suggestions are included. Please give me more comments if you have any concern. Thank you.

The biggest change is that I removed the detail about the rendering method. In original proposal we put most of the fragment shader code into getOpacity function, and the function is implemented together with a surface shader. It seems it is not the purpose of the material shader. So do you think that we should directly add a default and complete implementation in text.glslfx, and if the user would like to use a different implementation, they will modify the text.glslfx and add their own implementation?

**Comment by meshula** [comment]
Thanks for the update Pierre! 

> It seems it is not the purpose of the material shader. So do you think that we should directly add a default and complete implementation in text.glslfx, and if the user would like to use a different implementation, they will modify the text.glslfx and add their own implementation?

Yes, this is what I personally would hope for. The reason I want this is that I personally would prefer to have exact control of text shading and rendition, with opacity and color being computed jointly in order that I may perfectly control aliasing.

**Review by meshula — APPROVED** [review]
This is a substantial improvement! Thank you for your attention to detail.

I'm going to leave this open a little longer before merging in order that others may comment.

**Comment by PierreWang** [comment]
Hi @meshula . I found an issue with the proposal. In the future we are going to implement MSDF for the rendering of text. We need to create a texture and the texture will be used as a shader resource. So the text primitive still need to bind a material. Without the material binding, I don't know how to use a texture as a shader resource in USD.

**Comment by PierreWang** [comment]
We have created two prs for the schemas of SimpleText and MarkupText.
The schema for SimpleText: https://github.com/PixarAnimationStudios/OpenUSD/pull/3258
The schema for MarkupText: https://github.com/PixarAnimationStudios/OpenUSD/pull/3259

**Pull request merged**
