### PR TITLE
Autodesk: Add LineStyle proposal

### PR DESCRIPTION
**Pull request by erikaharrison-adsk**
### Description of Proposal

This is [a proposal](https://github.com/autodesk-forks/USD-proposals/blob/adsk/feature/LineStyle/proposals/LineStyle/README.md) on supporting line styles within OpenUSD. 

### Supporting Materials

N/A

### Contributing

- [X] I agree to and accept the [Supplemental Terms](https://graphics.pixar.com/usd/release/contributing_supplemental.html).

### CODE REVIEW

**Review by meshula — APPROVED** [review]
This PR is in the proper form, thank you; approving to unblock github workflows.

**Comment by meshula** [comment]
Could you revise the commit to include the signing requirement, then force push your branch? That should unblock the Merging workflow flag.

**Comment by erikaharrison-adsk** [comment]
@meshula - sorry for the delay, I didn't notice it was approved. Do we go ahead and merge it in ourselves? I know with the USD repo, we don't have permissions to do so, and here only those with write access can merge pull requests.

Please advise on next steps for this work, thanks!

**Comment by asluk** [comment]
These are all great features; thanks! I'd be interested in opening a discussion around the tradeoffs of having all of these properties live directly on the BasisCurves schema. Would it be worth considering other approaches like putting screen space and styling properties into API schemas? My concern is that the basis curves schema is already a bit muddled in its domain usage, and carving up its domain usages across API schemas as mixins might promote clarity around its role in a given scene? Thanks for considering!

**Comment by spiffmon** [comment]
> These are all great features; thanks! I'd be interested in opening a discussion around the tradeoffs of having all of these properties live directly on the BasisCurves schema. Would it be worth considering other approaches like putting screen space and styling properties into API schemas? My concern is that the basis curves schema is already a bit muddled in its domain usage, and carving up its domain usages across API schemas as mixins might promote clarity around its role in a given scene? Thanks for considering!

+1 to everything @asluk said.  Factoring these concerns into an applied schema will simplify the proposal, because there will no longer be a need for a `"none"` value of `style` - style is only considered when the schema is present on a Curves primitive.  **Plus**, that opens the door to applying the styling to `NurbsCurves`, as well as any other curve primitives that may come along.

I also think it will really strengthen the proposal to review and consider/contrast related art and use-cases.  For example, we already know there is interest in encoding [Blender's Grease Pencil](https://www.blender.org/features/story-artist/#grease-pencil-object) drawings in USD.  What about Tiltbrush?  And I also believe Adobe is interested in line-art.

It's great that you discuss the Hydra screenspace-related primvars, and I would love to see part of this proposal be either appropriately formalizing them in USD, or declaring they are no longer needed.  

This leads to another question: should "line styling" and "screen-space rendering" be formalized as separate concerns?  Thinking about Tiltbrush or wanting to put vector drawing on the side of a 3D building... if rich styling of lines only makes sense for 2D lines, let's state that, but even if so, it need not be limited to screen-space, but to any surface.  Does that argue for a 2D styled curve encoding, or are styled 3D curves still a needed thing?

Last thing is about the longer-term vision for styling: the proposal states the current implementation only supports linear curves.  Would you _plan_ to extend it to handle all the supported bases?  This proposal is a great treatment of some needed features, but it would really helpful to discuss, in the ways described above, how it fits into the future-looking needs of the USD ecosystem.

Thank you!

**Comment by meshula** [comment]
Hi @erikaharrison-adsk "approving" is a github workflow term in this case. We don't approve things for implementation into OpenUsd here! It's approved in order that we can land the proposal into this repo, to make it easier for others to help work on it. 

Without approve and merge, if others want to work on it, they need to fork YOUR repo, they would make requests onto it, and then you'd have to land on your repo, and propagate those changes here.

So, if we want, we can merge the proposal as we have done for other proposals, in order to facilitate collaboration...

**Comment by erikaharrison-adsk** [comment]
Thanks for the comments here - sorry for the delay responding. We'll follow up on the responses from @asluk and @spiffmon shortly. 

@meshula re: "merge the proposal to facilitate collaboration" -- ??? I'm sorry, I'm not following. I thought that this repo was about discussing features on the theoretical side (and practical if implementation is visible) via comments in PRs, and then once "approved" to be going ahead with getting the implementation out to OpenUSD. Is this not how it works? I'm not sure how approve & merge in this proposal repo impacts collaborations -- do you mean for others to be making changes to this branch and proposal files? Given there's feedback above, I'd assume we'll continue to update this proposal before merging this branch in. Thanks for your patience in helping me understand this better.

**Comment by meshula** [comment]
@erikaharrison-adsk Please refer to this section on the front page https://github.com/PixarAnimationStudios/OpenUSD-proposals/tree/main#relationship-to-other-forums which tries to lay out that this forum is for discussion. In this section https://github.com/PixarAnimationStudios/OpenUSD-proposals/tree/main#discuss-the-proposal we try to explain that this is a discussion and collaboration forum for proposals, but doesn't make any suggestion that an accepted proposal is also planned for implementation in OpenUSD.

Could you take a look over here? https://github.com/PixarAnimationStudios/OpenUSD-proposals/blob/main/proposals/Readme.md

That table shows the status of the proposals. As you can see the statuses are "Implemented", "Published", and "Draft".

LineStyles is not in the table! If we approve the PR here, we are specifically approving it for inclusion in that table, and assigning it a status.

"Implemented" means that it was implemented in OpenUSD itself.

"Published" means that it has achieved stability, and further work on the proposal is not expected. It does not mean that it will be implemented into OpenUSD, and also, it does not mean that will not be implemented. It just means that everyone has agreed that they think they've said everything they want to say about it. Presumably, interested parties are working on them, and will send them to the OpenUSD repo as a PR when they think they they are ready.

"Draft" means the proposal is in its working stage.

So an approval here on this page means, the proposal will appear on that page with a status. If everyone has agreed "hey LineStyle is ready to implement, there's nothing else to say" it would bear a "Published Status", and if there is ongoing conversation it would be marked as "Draft", meaning that there is still ongoing conversation, and cooperation and feedback is requested and encouraged.

As long as your proposal is here, as a PR, we can all comment, and you can update your PR as you wish. At the point you are ready to others proposing their own PRs on the proposal (as opposed to updating this PR yourself), then we can hit the Merge Pull Request button, and then everyone can collaborate directly on the button. We can't hit the Merge Pull request without also clicking the "github Approve" button, it's regrettable that that one word is so overloaded with unrelated meanings.

So... my hitting approval meant that I think we're ready to move to the "community collaboration" phase, and we'd move the status in the table to "Draft" or "Published" depending on consensus.

I hope this straightens things up. If it would help to improve the wording on the landing page to make it more understandable, suggestions are welcome.

**Comment by erikaharrison-adsk** [comment]
@meshula -- sorry to be a bother, but based on your [comment](https://github.com/PixarAnimationStudios/OpenUSD-proposals/pull/20#issuecomment-1842075185), and that you've approved this, should we now be listed as **Draft** on the [readme.md](https://github.com/PixarAnimationStudios/OpenUSD-proposals/blob/main/proposals/Readme.md) page? Or that only happens once this PR is merged? 

Or does this PR need to be updated to include the row in the Readme.md page?

**Comment by meshula** [comment]
@erikaharrison-adsk The listing on on the readme.md page gets updated when merged. You can add the row in the PR if you like, or we can do it for you upon merging. Just let us know when you'd like to merge :)

**Comment by erikaharrison-adsk** [comment]
Thanks @meshula -- we're good to merge this proposal in. @PierreWang will follow up in the new year with edits for this proposal based on the comments above.

**Comment by meshula** [comment]
Awesome :D

**Comment by erikaharrison-adsk** [comment]
@meshula (not sure how else to connect/tag you) - I'm not sure exactly what the next steps are at this stage. From our end, we're continuing to work on implementation and will get out a PR to OpenUSD in the coming weeks. From the proposal perspective, please advise what next we need to do, if there are specific things we ought to do.

**Comment by meshula** [comment]
Hi Erika, are you on the ASWF Slack? The easiest thing would be to connect there via a DM, and we can get a more direct conversation going. https://join.slack.com/t/academysoftwarefdn/shared_invite/zt-2at1248ps-UzGbBrikPTGS6TsODfYphg

**Pull request merged**
